version: "3"

services:
  web_app:
    container_name: web_app_prod
    build:
      context: .
      dockerfile: docker/prod/web_app/Dockerfile
    volumes:
      - ./app:/app
      - staticfiles:/home/app/staticfiles
    expose:
      - 8000
    command: gunicorn -w 3 blackroq.wsgi -b 0.0.0.0:8000
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    container_name: new_way_db_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    # environment:
    #   - SQL_DATABASE=newway
    #   - SQL_USER=newway
    #   - SQL_PASSWORD="newway"
    #   - SQL_HOST=db
    #   - SQL_PORT=5432

    ports:
      - 5435:5432

  nginx:
    container_name: new_way_nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - staticfiles:/home/app/staticfiles
    depends_on:
      - web_app

volumes:
  postgres_data:
  staticfiles:
