# Generated by Django 3.0 on 2020-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200403_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('FR', 'Featured'), ('RE', 'Rent')], default='SL', max_length=10),
        ),
    ]
